# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_remove_quote_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(related_name='users_favorites', to='belt_exam_app.User'),
        ),
    ]
