# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0003_auto_20171025_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(related_name='favorites', to='belt_exam_app.User'),
        ),
    ]
