# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0005_auto_20171025_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_quotes', to='belt_exam_app.User'),
        ),
    ]
